//
// CCU registers
//

#pragma once

#include <reg/regs_base.h>

// PLL_CPUX_CTRL_REG
#define PLL_CPUX_CTRL_REG 0x0000
#define PLL_CPUX_CTRL_REG_PLL_ENABLE 31
#define PLL_CPUX_CTRL_REG_LOCK 28
#define PLL_CPUX_CTRL_REG_CPUX_SDM_EN 24
#define PLL_CPUX_CTRL_REG_PLL_OUT_EXT_DIVP_HIGH 17
#define PLL_CPUX_CTRL_REG_PLL_OUT_EXT_DIVP_LOW 16
#define PLL_CPUX_CTRL_REG_PLL_FACTOR_N_HIGH 12
#define PLL_CPUX_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_CPUX_CTRL_REG_PLL_FACTOR_K_HIGH 5
#define PLL_CPUX_CTRL_REG_PLL_FACTOR_K_LOW 4
#define PLL_CPUX_CTRL_REG_PLL_FACTOR_M_HIGH 1
#define PLL_CPUX_CTRL_REG_PLL_FACTOR_M_LOW 0

// PLL_AUDIO_CTRL_REG
#define PLL_AUDIO_CTRL_REG 0x0008
#define PLL_AUDIO_CTRL_REG_PLL_ENABLE 31
#define PLL_AUDIO_CTRL_REG_LOCK 28
#define PLL_AUDIO_CTRL_REG_PLL_SDM_EN 24
#define PLL_AUDIO_CTRL_REG_PLL_POSTDIV_P_HIGH 19
#define PLL_AUDIO_CTRL_REG_PLL_POSTDIV_P_LOW 16
#define PLL_AUDIO_CTRL_REG_PLL_FACTOR_N_HIGH 14
#define PLL_AUDIO_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_AUDIO_CTRL_REG_PLL_PREDIV_M_HIGH 4
#define PLL_AUDIO_CTRL_REG_PLL_PREDIV_M_LOW 0

// PLL_VIDEO_CTRL_REG
#define PLL_VIDEO_CTRL_REG 0x0010
#define PLL_VIDEO_CTRL_REG_PLL_ENABLE 31
#define PLL_VIDEO_CTRL_REG_PLL_MODE 30
#define PLL_VIDEO_CTRL_REG_LOCK 28
#define PLL_VIDEO_CTRL_REG_FRAC_CLK_OUT 25
#define PLL_VIDEO_CTRL_REG_PLL_MODE_SEL 24
#define PLL_VIDEO_CTRL_REG_PLL_SDM_EN 20
#define PLL_VIDEO_CTRL_REG_PLL_FACTOR_N_HIGH 14
#define PLL_VIDEO_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_VIDEO_CTRL_REG_PLL_PREDIV_M_HIGH 3
#define PLL_VIDEO_CTRL_REG_PLL_PREDIV_M_LOW 0

// PLL_VE_CTRL_REG
#define PLL_VE_CTRL_REG 0x0018
#define PLL_VE_CTRL_REG_PLL_ENABLE 31
#define PLL_VE_CTRL_REG_LOCK 28
#define PLL_VE_CTRL_REG_FRAC_CLK_OUT 25
#define PLL_VE_CTRL_REG_PLL_MODE_SEL 24
#define PLL_VE_CTRL_REG_PLL_SDM_EN 20
#define PLL_VE_CTRL_REG_PLL_FACTOR_N_HIGH 14
#define PLL_VE_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_VE_CTRL_REG_PLL_PREDIV_M_HIGH 3
#define PLL_VE_CTRL_REG_PLL_PREDIV_M_LOW 0

// PLL_DDR_CTRL_REG
#define PLL_DDR_CTRL_REG 0x0020
#define PLL_DDR_CTRL_REG_PLL_ENABLE 31
#define PLL_DDR_CTRL_REG_LOCK 28
#define PLL_DDR_CTRL_REG_PLL_SDM_EN 24
#define PLL_DDR_CTRL_REG_PLL_DDR_CFG_UPDATE 20
#define PLL_DDR_CTRL_REG_PLL_FACTOR_N_HIGH 12
#define PLL_DDR_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_DDR_CTRL_REG_PLL_FACTOR_K_HIGH 5
#define PLL_DDR_CTRL_REG_PLL_FACTOR_K_LOW 4
#define PLL_DDR_CTRL_REG_PLL_FACTOR_M_HIGH 1
#define PLL_DDR_CTRL_REG_PLL_FACTOR_M_LOW 0

// PLL_PERIPH0_CTRL_REG
#define PLL_PERIPH0_CTRL_REG 0x0028
#define PLL_PERIPH0_CTRL_REG_PLL_ENABLE 31
#define PLL_PERIPH0_CTRL_REG_LOCK 28
#define PLL_PERIPH0_CTRL_REG_PLL_BYPASS_EN 25
#define PLL_PERIPH0_CTRL_REG_PLL_CLK_OUT_EN 24
#define PLL_PERIPH0_CTRL_REG_PLL_24M_OUT_EN 18
#define PLL_PERIPH0_CTRL_REG_PLL_24M_POST_DIV_HIGH 17
#define PLL_PERIPH0_CTRL_REG_PLL_24M_POST_DIV_LOW 16
#define PLL_PERIPH0_CTRL_REG_PLL_FACTOR_N_HIGH 12
#define PLL_PERIPH0_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_PERIPH0_CTRL_REG_PLL_FACTOR_K_HIGH 5
#define PLL_PERIPH0_CTRL_REG_PLL_FACTOR_K_LOW 4
#define PLL_PERIPH0_CTRL_REG_PLL_FACTOR_M_HIGH 1
#define PLL_PERIPH0_CTRL_REG_PLL_FACTOR_M_LOW 0

// PLL_GPU_CTRL_REG
#define PLL_GPU_CTRL_REG 0x0038
#define PLL_GPU_CTRL_REG_PLL_ENABLE 31
#define PLL_GPU_CTRL_REG_LOCK 28
#define PLL_GPU_CTRL_REG_FRAC_CLK_OUT 25
#define PLL_GPU_CTRL_REG_PLL_MODE_SEL 24
#define PLL_GPU_CTRL_REG_PLL_SDM_EN 20
#define PLL_GPU_CTRL_REG_PLL_FACTOR_N_HIGH 14
#define PLL_GPU_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_GPU_CTRL_REG_PLL_PRE_DIV_M_HIGH 3
#define PLL_GPU_CTRL_REG_PLL_PRE_DIV_M_LOW 0

// PLL_PERIPH1_CTRL_REG
#define PLL_PERIPH1_CTRL_REG 0x0044
#define PLL_PERIPH1_CTRL_REG_PLL_ENABLE 31
#define PLL_PERIPH1_CTRL_REG_LOCK 28
#define PLL_PERIPH1_CTRL_REG_PLL_BYPASS_EN 25
#define PLL_PERIPH1_CTRL_REG_PLL_CLK_OUT_EN 24
#define PLL_PERIPH1_CTRL_REG_PLL_SDM_EN 20
#define PLL_PERIPH1_CTRL_REG_PLL_24M_OUT_EN 18
#define PLL_PERIPH1_CTRL_REG_PLL_24M_POST_DIV_HIGH 17
#define PLL_PERIPH1_CTRL_REG_PLL_24M_POST_DIV_LOW 16
#define PLL_PERIPH1_CTRL_REG_PLL_FACTOR_N_HIGH 12
#define PLL_PERIPH1_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_PERIPH1_CTRL_REG_PLL_FACTOR_K_HIGH 5
#define PLL_PERIPH1_CTRL_REG_PLL_FACTOR_K_LOW 4
#define PLL_PERIPH1_CTRL_REG_PLL_FACTOR_M_HIGH 1
#define PLL_PERIPH1_CTRL_REG_PLL_FACTOR_M_LOW 0

// PLL_DE_CTRL_REG
#define PLL_DE_CTRL_REG 0x0048
#define PLL_DE_CTRL_REG_PLL_ENABLE 31
#define PLL_DE_CTRL_REG_LOCK 28
#define PLL_DE_CTRL_REG_FRAC_CLK_OUT 25
#define PLL_DE_CTRL_REG_PLL_MODE_SEL 24
#define PLL_DE_CTRL_REG_PLL_SDM_EN 20
#define PLL_DE_CTRL_REG_PLL_FACTOR_N_HIGH 14
#define PLL_DE_CTRL_REG_PLL_FACTOR_N_LOW 8
#define PLL_DE_CTRL_REG_PLL_PRE_DIV_M_HIGH 3
#define PLL_DE_CTRL_REG_PLL_PRE_DIV_M_LOW 0

// CPUX_AXI_CFG_REG
#define CPUX_AXI_CFG_REG 0x0050
#define CPUX_AXI_CFG_REG_CPUX_CLK_SRC_SEL_HIGH 17
#define CPUX_AXI_CFG_REG_CPUX_CLK_SRC_SEL_LOW 16
#define CPUX_AXI_CFG_REG_CPU_APB_CLK_DIV_HIGH 9
#define CPUX_AXI_CFG_REG_CPU_APB_CLK_DIV_LOW 8
#define CPUX_AXI_CFG_REG_AXI_CLK_DIV_RATIO_HIGH 1
#define CPUX_AXI_CFG_REG_AXI_CLK_DIV_RATIO_LOW 0

// AHB1_APB1_CFG_REG
#define AHB1_APB1_CFG_REG 0x0054
#define AHB1_APB1_CFG_REG_AHB1_CLK_SRC_SEL_HIGH 13
#define AHB1_APB1_CFG_REG_AHB1_CLK_SRC_SEL_LOW 12
#define AHB1_APB1_CFG_REG_APB1_CLK_RATIO_HIGH 9
#define AHB1_APB1_CFG_REG_APB1_CLK_RATIO_LOW 8
#define AHB1_APB1_CFG_REG_AHB1_PRE_DIV_HIGH 7
#define AHB1_APB1_CFG_REG_AHB1_PRE_DIV_LOW 6
#define AHB1_APB1_CFG_REG_AHB1_CLK_DIV_RATIO_HIGH 5
#define AHB1_APB1_CFG_REG_AHB1_CLK_DIV_RATIO_LOW 4

// APB2_CFG_REG
#define APB2_CFG_REG 0x0058
#define APB2_CFG_REG_APB2_CLK_SRC_SEL_HIGH 25
#define APB2_CFG_REG_APB2_CLK_SRC_SEL_LOW 24
#define APB2_CFG_REG_CLK_RAT_N_HIGH 17
#define APB2_CFG_REG_CLK_RAT_N_LOW 16
#define APB2_CFG_REG_CLK_RAT_M_HIGH 4
#define APB2_CFG_REG_CLK_RAT_M_LOW 0

// AHB2_CFG_REG
#define AHB2_CFG_REG 0x005C
#define AHB2_CFG_REG_AHB2_CLK_CFG_HIGH 1
#define AHB2_CFG_REG_AHB2_CLK_CFG_LOW 0

// BUS_CLK_GATING_REG0
#define BUS_CLK_GATING_REG0 0x0060
#define BUS_CLK_GATING_REG0_USBOHCI3_GATING 31
#define BUS_CLK_GATING_REG0_USBOHCI2_GATING 30
#define BUS_CLK_GATING_REG0_USBOHCI1_GATING 29
#define BUS_CLK_GATING_REG0_USB 28
#define BUS_CLK_GATING_REG0_USBEHCI3_GATING 27
#define BUS_CLK_GATING_REG0_USBEHCI2_GATING 26
#define BUS_CLK_GATING_REG0_USBEHCI1_GATING 25
#define BUS_CLK_GATING_REG0_USB_OTG_EHCI0_GATING 24
#define BUS_CLK_GATING_REG0_USB_OTG_DEVICE_GATING 23
#define BUS_CLK_GATING_REG0_SPI1_GATING 21
#define BUS_CLK_GATING_REG0_SPI0_GATING 20
#define BUS_CLK_GATING_REG0_HSTMR_GATING 19
#define BUS_CLK_GATING_REG0_TS_GATING 18
#define BUS_CLK_GATING_REG0_EMAC_GATING 17
#define BUS_CLK_GATING_REG0_DRAM_GATING 14
#define BUS_CLK_GATING_REG0_NAND_GATING 13
#define BUS_CLK_GATING_REG0_MMC2_GATING 10
#define BUS_CLK_GATING_REG0_MMC1_GATING 9
#define BUS_CLK_GATING_REG0_MMC0_GATING 8
#define BUS_CLK_GATING_REG0_DMA_GATING 6
#define BUS_CLK_GATING_REG0_CE_GATING 5

// BUS_CLK_GATING_REG1
#define BUS_CLK_GATING_REG1 0x0064
#define BUS_CLK_GATING_REG1_SPINLOCK_GATING 22
#define BUS_CLK_GATING_REG1_MSGBOX_GATING 21
#define BUS_CLK_GATING_REG1_GPU_GATING 20
#define BUS_CLK_GATING_REG1_DE_GATING 12
#define BUS_CLK_GATING_REG1_HDMI_GATING 11
#define BUS_CLK_GATING_REG1_TVE_GATING 9
#define BUS_CLK_GATING_REG1_CSI_GATING 8
#define BUS_CLK_GATING_REG1_DEINTERLACE_GATING 5
#define BUS_CLK_GATING_REG1_TCON1_GATING 4
#define BUS_CLK_GATING_REG1_TCON0_GATING 3
#define BUS_CLK_GATING_REG1_VE_GATING 0

// BUS_CLK_GATING_REG2
#define BUS_CLK_GATING_REG2 0x0068
#define BUS_CLK_GATING_REG2_I2S_PCM_2_GATING 14
#define BUS_CLK_GATING_REG2_I2S_PCM_1_GATING 13
#define BUS_CLK_GATING_REG2_I2S_PCM_0_GATING 12
#define BUS_CLK_GATING_REG2_THS_GATING 8
#define BUS_CLK_GATING_REG2_PIO_GATING 5
#define BUS_CLK_GATING_REG2_OWA_GATING 1
#define BUS_CLK_GATING_REG2_AC_DIG_GATING 0

// BUS_CLK_GATING_REG3
#define BUS_CLK_GATING_REG3 0x006C
#define BUS_CLK_GATING_REG3_SCR_GATING 20
#define BUS_CLK_GATING_REG3_UART3_GATING 19
#define BUS_CLK_GATING_REG3_UART2_GATING 18
#define BUS_CLK_GATING_REG3_UART1_GATING 17
#define BUS_CLK_GATING_REG3_UART0_GATING 16
#define BUS_CLK_GATING_REG3_TWI2_GATING 2
#define BUS_CLK_GATING_REG3_TWI1_GATING 1
#define BUS_CLK_GATING_REG3_TWI0_GATING 0

// BUS_CLK_GATING_REG4
#define BUS_CLK_GATING_REG4 0x0070
#define BUS_CLK_GATING_REG4_DBGSYS_GATING 7
#define BUS_CLK_GATING_REG4_EPHY_GATING 0

// THS_CLK_REG
#define THS_CLK_REG 0x0074
#define THS_CLK_REG_SCLK_GATING 31
#define THS_CLK_REG_THS_CLK_SRC_SEL_HIGH 25
#define THS_CLK_REG_THS_CLK_SRC_SEL_LOW 24
#define THS_CLK_REG_THS_CLK_DIV_RATIO_HIGH 1
#define THS_CLK_REG_THS_CLK_DIV_RATIO_LOW 0

// NAND_CLK_REG
#define NAND_CLK_REG 0x0080
#define NAND_CLK_REG_SCLK_GATING 31
#define NAND_CLK_REG_CLK_SRC_SEL_HIGH 25
#define NAND_CLK_REG_CLK_SRC_SEL_LOW 24
#define NAND_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define NAND_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define NAND_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define NAND_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// SDMMC0_CLK_REG
#define SDMMC0_CLK_REG 0x0088
#define SDMMC0_CLK_REG_SCLK_GATING 31
#define SDMMC0_CLK_REG_CLK_SRC_SEL_HIGH 25
#define SDMMC0_CLK_REG_CLK_SRC_SEL_LOW 24
#define SDMMC0_CLK_REG_SAMPLE_CLK_PHASE_CTR_HIGH 22
#define SDMMC0_CLK_REG_SAMPLE_CLK_PHASE_CTR_LOW 20
#define SDMMC0_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define SDMMC0_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define SDMMC0_CLK_REG_OUTPUT_CLK_PHASE_CTR_HIGH 10
#define SDMMC0_CLK_REG_OUTPUT_CLK_PHASE_CTR_LOW 8
#define SDMMC0_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define SDMMC0_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// SDMMC1_CLK_REG
#define SDMMC1_CLK_REG 0x008C
#define SDMMC1_CLK_REG_SCLK_GATING 31
#define SDMMC1_CLK_REG_MMC1_MODE_SELECT 30
#define SDMMC1_CLK_REG_CLK_SRC_SEL_HIGH 25
#define SDMMC1_CLK_REG_CLK_SRC_SEL_LOW 24
#define SDMMC1_CLK_REG_SAMPLE_CLK_PHASE_CTR_HIGH 22
#define SDMMC1_CLK_REG_SAMPLE_CLK_PHASE_CTR_LOW 20
#define SDMMC1_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define SDMMC1_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define SDMMC1_CLK_REG_OUTPUT_CLK_PHASE_CTR_HIGH 10
#define SDMMC1_CLK_REG_OUTPUT_CLK_PHASE_CTR_LOW 8
#define SDMMC1_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define SDMMC1_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// SDMMC2_CLK_REG
#define SDMMC2_CLK_REG 0x0090
#define SDMMC2_CLK_REG_SCLK_GATING 31
#define SDMMC2_CLK_REG_MMC2_MODE_SELECT 30
#define SDMMC2_CLK_REG_CLK_SRC_SEL_HIGH 25
#define SDMMC2_CLK_REG_CLK_SRC_SEL_LOW 24
#define SDMMC2_CLK_REG_CLK_PHASE_CTR_HIGH 22
#define SDMMC2_CLK_REG_CLK_PHASE_CTR_LOW 20
#define SDMMC2_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define SDMMC2_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define SDMMC2_CLK_REG_OUTPUT_CLK_PHASE_CTR_HIGH 10
#define SDMMC2_CLK_REG_OUTPUT_CLK_PHASE_CTR_LOW 8
#define SDMMC2_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define SDMMC2_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// TS_CLK_REG
#define TS_CLK_REG 0x0098
#define TS_CLK_REG_SCLK_GATING 31
#define TS_CLK_REG_CLK_SRC_SEL_HIGH 27
#define TS_CLK_REG_CLK_SRC_SEL_LOW 24
#define TS_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define TS_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define TS_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define TS_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// CE_CLK_REG
#define CE_CLK_REG 0x009C
#define CE_CLK_REG_SCLK_GATING 31
#define CE_CLK_REG_CLK_SRC_SEL_HIGH 25
#define CE_CLK_REG_CLK_SRC_SEL_LOW 24
#define CE_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define CE_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define CE_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define CE_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// SPI0_CLK_REG
#define SPI0_CLK_REG 0x00A0
#define SPI0_CLK_REG_SCLK_GATING 31
#define SPI0_CLK_REG_CLK_SRC_SEL_HIGH 25
#define SPI0_CLK_REG_CLK_SRC_SEL_LOW 24
#define SPI0_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define SPI0_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define SPI0_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define SPI0_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// SPI1_CLK_REG
#define SPI1_CLK_REG 0x00A4
#define SPI1_CLK_REG_SCLK_GATING 31
#define SPI1_CLK_REG_CLK_SRC_SEL_HIGH 25
#define SPI1_CLK_REG_CLK_SRC_SEL_LOW 24
#define SPI1_CLK_REG_CLK_DIV_RATIO_N_HIGH 17
#define SPI1_CLK_REG_CLK_DIV_RATIO_N_LOW 16
#define SPI1_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define SPI1_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// I2S_PCM_0_CLK_REG
#define I2S_PCM_0_CLK_REG 0x00B0
#define I2S_PCM_0_CLK_REG_SCLK_GATING 31
#define I2S_PCM_0_CLK_REG_CLK_SRC_SEL_HIGH 17
#define I2S_PCM_0_CLK_REG_CLK_SRC_SEL_LOW 16

// I2S_PCM_1_CLK_REG
#define I2S_PCM_1_CLK_REG 0x00B4
#define I2S_PCM_1_CLK_REG_SCLK_GATING 31
#define I2S_PCM_1_CLK_REG_CLK_SRC_SEL_HIGH 17
#define I2S_PCM_1_CLK_REG_CLK_SRC_SEL_LOW 16

// I2S_PCM_2_CLK_REG
#define I2S_PCM_2_CLK_REG 0x00B8
#define I2S_PCM_2_CLK_REG_SCLK_GATING 31
#define I2S_PCM_2_CLK_REG_CLK_SRC_SEL_HIGH 17
#define I2S_PCM_2_CLK_REG_CLK_SRC_SEL_LOW 16

// OWA_CLK_REG
#define OWA_CLK_REG 0x00C0
#define OWA_CLK_REG_SCLK_GATING 31
#define OWA_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define OWA_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// USBPHY_CFG_REG
#define USBPHY_CFG_REG 0x00CC
#define USBPHY_CFG_REG_SCLK_GATING_OHCI3 19
#define USBPHY_CFG_REG_SCLK_GATING_OHCI2 18
#define USBPHY_CFG_REG_SCLK_GATING_OHCI1 17
#define USBPHY_CFG_REG_SCLK_GATING_OTG_OHCI0 16
#define USBPHY_CFG_REG_SCLK_GATING_USBPHY3 11
#define USBPHY_CFG_REG_SCLK_GATING_USBPHY2 10
#define USBPHY_CFG_REG_SCLK_GATING_USBPHY1 9
#define USBPHY_CFG_REG_SCLK_GATING_USBPHY0 8
#define USBPHY_CFG_REG_USBPHY3_RST 3
#define USBPHY_CFG_REG_USBPHY2_RST 2
#define USBPHY_CFG_REG_USBPHY1_RST 1
#define USBPHY_CFG_REG_USBPHY0_RST 0

// DRAM_CFG_REG
#define DRAM_CFG_REG 0x00F4
#define DRAM_CFG_REG_DRAM_CTR_RST 31
#define DRAM_CFG_REG_CLK_SRC_SEL_HIGH 21
#define DRAM_CFG_REG_CLK_SRC_SEL_LOW 20
#define DRAM_CFG_REG_SDRCLK_UPD 16
#define DRAM_CFG_REG_DRAM_DIV_M_HIGH 3
#define DRAM_CFG_REG_DRAM_DIV_M_LOW 0

// MBUS_RST_REG
#define MBUS_RST_REG 0x00FC
#define MBUS_RST_REG_MBUS_RESET 31

// DRAM_CLK_GATING_REG
#define DRAM_CLK_GATING_REG 0x0100
#define DRAM_CLK_GATING_REG_TS_DCLK_GATING 3
#define DRAM_CLK_GATING_REG_DEINTERLACE_DCLK_GATING 2
#define DRAM_CLK_GATING_REG_CSI_DCLK_GATING 1
#define DRAM_CLK_GATING_REG_VE_DCLK_GATING 0

// DE_CLK_REG
#define DE_CLK_REG 0x0104
#define DE_CLK_REG_SCLK_GATING 31
#define DE_CLK_REG_CLK_SRC_SEL_HIGH 26
#define DE_CLK_REG_CLK_SRC_SEL_LOW 24
#define DE_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define DE_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// TCON0_CLK_REG
#define TCON0_CLK_REG 0x0118
#define TCON0_CLK_REG_SCLK_GATING 31
#define TCON0_CLK_REG_CLK_SRC_SEL_HIGH 26
#define TCON0_CLK_REG_CLK_SRC_SEL_LOW 24
#define TCON0_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define TCON0_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// TVE_CLK_REG
#define TVE_CLK_REG 0x0120
#define TVE_CLK_REG_SCLK_GATING 31
#define TVE_CLK_REG_CLK_SRC_SEL_HIGH 26
#define TVE_CLK_REG_CLK_SRC_SEL_LOW 24
#define TVE_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define TVE_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// DEINTERLACE_CLK_REG
#define DEINTERLACE_CLK_REG 0x0124
#define DEINTERLACE_CLK_REG_SCLK_GATING 31
#define DEINTERLACE_CLK_REG_CLK_SRC_SEL_HIGH 26
#define DEINTERLACE_CLK_REG_CLK_SRC_SEL_LOW 24
#define DEINTERLACE_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define DEINTERLACE_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// CSI_MISC_CLK_REG
#define CSI_MISC_CLK_REG 0x0130
#define CSI_MISC_CLK_REG_MIPI_CSI_CFG 31

// CSI_CLK_REG
#define CSI_CLK_REG 0x0134
#define CSI_CLK_REG_CSI_SCLK_GATING 31
#define CSI_CLK_REG_SCLK_SRC_SEL_HIGH 26
#define CSI_CLK_REG_SCLK_SRC_SEL_LOW 24
#define CSI_CLK_REG_CSI_SCLK_DIV_M_HIGH 19
#define CSI_CLK_REG_CSI_SCLK_DIV_M_LOW 16
#define CSI_CLK_REG_CSI_MCLK_GATING 15
#define CSI_CLK_REG_MCLK_SRC_SEL_HIGH 10
#define CSI_CLK_REG_MCLK_SRC_SEL_LOW 8
#define CSI_CLK_REG_CSI_MCLK_DIV_M_HIGH 4
#define CSI_CLK_REG_CSI_MCLK_DIV_M_LOW 0

// VE_CLK_REG
#define VE_CLK_REG 0x013C
#define VE_CLK_REG_VE_SCLK_GATING 31
#define VE_CLK_REG_CLK_DIV_RATIO_N_HIGH 18
#define VE_CLK_REG_CLK_DIV_RATIO_N_LOW 16

// AC_DIG_CLK_REG
#define AC_DIG_CLK_REG 0x0140
#define AC_DIG_CLK_REG_SCLK_1X_GATING 31

// AVS_CLK_REG
#define AVS_CLK_REG 0x0144
#define AVS_CLK_REG_SCLK_GATING 31

// HDMI_CLK_REG
#define HDMI_CLK_REG 0x0150
#define HDMI_CLK_REG_SCLK_GATING 31
#define HDMI_CLK_REG_SCLK_SEL_HIGH 25
#define HDMI_CLK_REG_SCLK_SEL_LOW 24
#define HDMI_CLK_REG_CLK_DIV_RATIO_M_HIGH 3
#define HDMI_CLK_REG_CLK_DIV_RATIO_M_LOW 0

// HDMI_SLOW_CLK_REG
#define HDMI_SLOW_CLK_REG 0x0154
#define HDMI_SLOW_CLK_REG_HDMI_DDC_CLK_GATING 31

// MBUS_CLK_REG
#define MBUS_CLK_REG 0x015C
#define MBUS_CLK_REG_MBUS_SCLK_GATING 31
#define MBUS_CLK_REG_MBUS_SCLK_SRC_HIGH 25
#define MBUS_CLK_REG_MBUS_SCLK_SRC_LOW 24
#define MBUS_CLK_REG_MBUS_SCLK_RATIO_M_HIGH 2
#define MBUS_CLK_REG_MBUS_SCLK_RATIO_M_LOW 0

// GPU_CLK_REG
#define GPU_CLK_REG 0x01A0
#define GPU_CLK_REG_SCLK_GATING 31
#define GPU_CLK_REG_CLK_DIV_RATIO_N_HIGH 2
#define GPU_CLK_REG_CLK_DIV_RATIO_N_LOW 0

// PLL_STABLE_TIME_REG0
#define PLL_STABLE_TIME_REG0 0x0200
#define PLL_STABLE_TIME_REG0_PLL_LOCK_TIME_HIGH 15
#define PLL_STABLE_TIME_REG0_PLL_LOCK_TIME_LOW 0

// PLL_STABLE_TIME_REG1
#define PLL_STABLE_TIME_REG1 0x0204
#define PLL_STABLE_TIME_REG1_PLL_CPU_LOCK_TIME_HIGH 15
#define PLL_STABLE_TIME_REG1_PLL_CPU_LOCK_TIME_LOW 0

// PLL_CPUX_BIAS_REG
#define PLL_CPUX_BIAS_REG 0x0220
#define PLL_CPUX_BIAS_REG_VCO_RST 31
#define PLL_CPUX_BIAS_REG_EXG_MODE 28
#define PLL_CPUX_BIAS_REG_PLL_VCO_BIAS_CTRL_HIGH 27
#define PLL_CPUX_BIAS_REG_PLL_VCO_BIAS_CTRL_LOW 24
#define PLL_CPUX_BIAS_REG_PLL_BIAS_CUR_CTRL_HIGH 20
#define PLL_CPUX_BIAS_REG_PLL_BIAS_CUR_CTRL_LOW 16
#define PLL_CPUX_BIAS_REG_PLL_LOCK_CTRL_HIGH 10
#define PLL_CPUX_BIAS_REG_PLL_LOCK_CTRL_LOW 8
#define PLL_CPUX_BIAS_REG_PLL_DAMP_FACT_CTRL_HIGH 3
#define PLL_CPUX_BIAS_REG_PLL_DAMP_FACT_CTRL_LOW 0

// PLL_AUDIO_BIAS_REG
#define PLL_AUDIO_BIAS_REG 0x0224
#define PLL_AUDIO_BIAS_REG_PLL_VCO_BIAS_HIGH 28
#define PLL_AUDIO_BIAS_REG_PLL_VCO_BIAS_LOW 24
#define PLL_AUDIO_BIAS_REG_PLL_BIAS_CUR_HIGH 20
#define PLL_AUDIO_BIAS_REG_PLL_BIAS_CUR_LOW 16

// PLL_VIDEO_BIAS_REG
#define PLL_VIDEO_BIAS_REG 0x0228
#define PLL_VIDEO_BIAS_REG_PLL_VCO_BIAS_CTRL_HIGH 28
#define PLL_VIDEO_BIAS_REG_PLL_VCO_BIAS_CTRL_LOW 24
#define PLL_VIDEO_BIAS_REG_PLL_BIAS_CTRL_HIGH 20
#define PLL_VIDEO_BIAS_REG_PLL_BIAS_CTRL_LOW 16
#define PLL_VIDEO_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 2
#define PLL_VIDEO_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_VE_BIAS_REG
#define PLL_VE_BIAS_REG 0x022C
#define PLL_VE_BIAS_REG_PLL_VCO_BIAS_CTRL_HIGH 28
#define PLL_VE_BIAS_REG_PLL_VCO_BIAS_CTRL_LOW 24
#define PLL_VE_BIAS_REG_PLL_BIAS_CTRL_HIGH 20
#define PLL_VE_BIAS_REG_PLL_BIAS_CTRL_LOW 16
#define PLL_VE_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 2
#define PLL_VE_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_DDR_BIAS_REG
#define PLL_DDR_BIAS_REG 0x0230
#define PLL_DDR_BIAS_REG_PLL_VCO_BIAS_HIGH 31
#define PLL_DDR_BIAS_REG_PLL_VCO_BIAS_LOW 28
#define PLL_DDR_BIAS_REG_PLL_VCO_GAIN_CTRL_EN 25
#define PLL_DDR_BIAS_REG_PLL_BANDW_CTRL 24
#define PLL_DDR_BIAS_REG_PLL_BIAS_CUR_CTRL_HIGH 20
#define PLL_DDR_BIAS_REG_PLL_BIAS_CUR_CTRL_LOW 16
#define PLL_DDR_BIAS_REG_PLL_VCO_GAIN_CTRL_HIGH 14
#define PLL_DDR_BIAS_REG_PLL_VCO_GAIN_CTRL_LOW 12
#define PLL_DDR_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 3
#define PLL_DDR_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_PERIPH0_BIAS_REG
#define PLL_PERIPH0_BIAS_REG 0x0234
#define PLL_PERIPH0_BIAS_REG_PLL_VCO_BIAS_HIGH 28
#define PLL_PERIPH0_BIAS_REG_PLL_VCO_BIAS_LOW 24
#define PLL_PERIPH0_BIAS_REG_PLL_BIAS_CUR_CTRL_HIGH 20
#define PLL_PERIPH0_BIAS_REG_PLL_BIAS_CUR_CTRL_LOW 16
#define PLL_PERIPH0_BIAS_REG_PLL_BANDW_CTRL 4
#define PLL_PERIPH0_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 1
#define PLL_PERIPH0_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_GPU_BIAS_REG
#define PLL_GPU_BIAS_REG 0x023C
#define PLL_GPU_BIAS_REG_PLL_VCO_BIAS_CTRL_HIGH 28
#define PLL_GPU_BIAS_REG_PLL_VCO_BIAS_CTRL_LOW 24
#define PLL_GPU_BIAS_REG_PLL_BIAS_CTRL_HIGH 20
#define PLL_GPU_BIAS_REG_PLL_BIAS_CTRL_LOW 16
#define PLL_GPU_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 2
#define PLL_GPU_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_PERIPH1_BIAS_REG
#define PLL_PERIPH1_BIAS_REG 0x0244
#define PLL_PERIPH1_BIAS_REG_PLL_VCO_BIAS_HIGH 28
#define PLL_PERIPH1_BIAS_REG_PLL_VCO_BIAS_LOW 24
#define PLL_PERIPH1_BIAS_REG_PLL_BIAS_CUR_CTRL_HIGH 20
#define PLL_PERIPH1_BIAS_REG_PLL_BIAS_CUR_CTRL_LOW 16
#define PLL_PERIPH1_BIAS_REG_PLL_BANDW_CTRL 4
#define PLL_PERIPH1_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 1
#define PLL_PERIPH1_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_DE_BIAS_REG
#define PLL_DE_BIAS_REG 0x0248
#define PLL_DE_BIAS_REG_PLL_VCO_BIAS_CTRL_HIGH 28
#define PLL_DE_BIAS_REG_PLL_VCO_BIAS_CTRL_LOW 24
#define PLL_DE_BIAS_REG_PLL_BIAS_CTRL_HIGH 20
#define PLL_DE_BIAS_REG_PLL_BIAS_CTRL_LOW 16
#define PLL_DE_BIAS_REG_PLL_DAMP_FACTOR_CTRL_HIGH 2
#define PLL_DE_BIAS_REG_PLL_DAMP_FACTOR_CTRL_LOW 0

// PLL_CPUX_TUN_REG
#define PLL_CPUX_TUN_REG 0x0250
#define PLL_CPUX_TUN_REG_PLL_BAND_WID_CTRL 27
#define PLL_CPUX_TUN_REG_VCO_GAIN_CTRL_EN 26
#define PLL_CPUX_TUN_REG_VCO_GAIN_CTRL_HIGH 25
#define PLL_CPUX_TUN_REG_VCO_GAIN_CTRL_LOW 23
#define PLL_CPUX_TUN_REG_PLL_INIT_FREQ_CTRL_HIGH 22
#define PLL_CPUX_TUN_REG_PLL_INIT_FREQ_CTRL_LOW 16
#define PLL_CPUX_TUN_REG_C_OD 15
#define PLL_CPUX_TUN_REG_C_B_IN_HIGH 14
#define PLL_CPUX_TUN_REG_C_B_IN_LOW 8
#define PLL_CPUX_TUN_REG_C_OD1 7
#define PLL_CPUX_TUN_REG_C_B_OUT_HIGH 6
#define PLL_CPUX_TUN_REG_C_B_OUT_LOW 0

// PLL_DDR_TUN_REG
#define PLL_DDR_TUN_REG 0x0260
#define PLL_DDR_TUN_REG_VREG1_OUT_EN 28
#define PLL_DDR_TUN_REG_PLL_LTIME_CTRL_HIGH 26
#define PLL_DDR_TUN_REG_PLL_LTIME_CTRL_LOW 24
#define PLL_DDR_TUN_REG_VCO_RST 23
#define PLL_DDR_TUN_REG_PLL_INIT_FREQ_CTRL_HIGH 22
#define PLL_DDR_TUN_REG_PLL_INIT_FREQ_CTRL_LOW 16
#define PLL_DDR_TUN_REG_OD1 15
#define PLL_DDR_TUN_REG_B_IN_HIGH 14
#define PLL_DDR_TUN_REG_B_IN_LOW 8
#define PLL_DDR_TUN_REG_OD 7
#define PLL_DDR_TUN_REG_B_OUT_HIGH 6
#define PLL_DDR_TUN_REG_B_OUT_LOW 0

// PLL_CPUX_PAT_CTRL_REG
#define PLL_CPUX_PAT_CTRL_REG 0x0280
#define PLL_CPUX_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_CPUX_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_CPUX_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_CPUX_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_CPUX_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_CPUX_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_CPUX_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_CPUX_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_CPUX_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_AUDIO_PAT_CTRL_REG
#define PLL_AUDIO_PAT_CTRL_REG 0x0284
#define PLL_AUDIO_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_AUDIO_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_AUDIO_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_AUDIO_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_AUDIO_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_AUDIO_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_AUDIO_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_AUDIO_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_AUDIO_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_VIDEO_PAT_CTRL_REG
#define PLL_VIDEO_PAT_CTRL_REG 0x0288
#define PLL_VIDEO_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_VIDEO_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_VIDEO_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_VIDEO_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_VIDEO_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_VIDEO_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_VIDEO_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_VIDEO_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_VIDEO_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_VE_PAT_CTRL_REG
#define PLL_VE_PAT_CTRL_REG 0x028C
#define PLL_VE_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_VE_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_VE_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_VE_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_VE_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_VE_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_VE_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_VE_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_VE_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_DDR_PAT_CTRL_REG
#define PLL_DDR_PAT_CTRL_REG 0x0290
#define PLL_DDR_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_DDR_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_DDR_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_DDR_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_DDR_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_DDR_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_DDR_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_DDR_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_DDR_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_GPU_PAT_CTRL_REG
#define PLL_GPU_PAT_CTRL_REG 0x029C
#define PLL_GPU_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_GPU_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_GPU_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_GPU_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_GPU_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_GPU_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_GPU_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_GPU_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_GPU_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_PERIPH1_PAT_CTRL_REG
#define PLL_PERIPH1_PAT_CTRL_REG 0x02A4
#define PLL_PERIPH1_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_PERIPH1_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_PERIPH1_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_PERIPH1_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_PERIPH1_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_PERIPH1_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_PERIPH1_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_PERIPH1_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_PERIPH1_PAT_CTRL_REG_WAVE_BOT_LOW 0

// PLL_DE_PAT_CTRL_REG
#define PLL_DE_PAT_CTRL_REG 0x02A8
#define PLL_DE_PAT_CTRL_REG_SIG_DELT_PAT_EN 31
#define PLL_DE_PAT_CTRL_REG_SPR_FREQ_MODE_HIGH 30
#define PLL_DE_PAT_CTRL_REG_SPR_FREQ_MODE_LOW 29
#define PLL_DE_PAT_CTRL_REG_WAVE_STEP_HIGH 28
#define PLL_DE_PAT_CTRL_REG_WAVE_STEP_LOW 20
#define PLL_DE_PAT_CTRL_REG_FREQ_HIGH 18
#define PLL_DE_PAT_CTRL_REG_FREQ_LOW 17
#define PLL_DE_PAT_CTRL_REG_WAVE_BOT_HIGH 16
#define PLL_DE_PAT_CTRL_REG_WAVE_BOT_LOW 0

// BUS_SOFT_RST_REG0confidential
#define BUS_SOFT_RST_REG0confidential 0x02C0
#define BUS_SOFT_RST_REG0confidential_USBOHCI3_RST 31
#define BUS_SOFT_RST_REG0confidential_USBOHCI2_RST 30
#define BUS_SOFT_RST_REG0confidential_USBOHCI1_RST 29
#define BUS_SOFT_RST_REG0confidential_USB_OTG_OHCI0_RST 28
#define BUS_SOFT_RST_REG0confidential_USBEHCI3_RST 27
#define BUS_SOFT_RST_REG0confidential_USBEHCI2_RST 26
#define BUS_SOFT_RST_REG0confidential_USBEHCI1_RST 25
#define BUS_SOFT_RST_REG0confidential_USB_OTG_EHCI0_RST 24
#define BUS_SOFT_RST_REG0confidential_USB_OTG_D 23
#define BUS_SOFT_RST_REG0confidential_SPI1_RST 21
#define BUS_SOFT_RST_REG0confidential_SPI0_RST 20
#define BUS_SOFT_RST_REG0confidential_HSTMR_RST 19
#define BUS_SOFT_RST_REG0confidential_TS_RST 18
#define BUS_SOFT_RST_REG0confidential_EMAC_RST 17
#define BUS_SOFT_RST_REG0confidential_SDRAM_RST 14
#define BUS_SOFT_RST_REG0confidential_NAND_RST 13
#define BUS_SOFT_RST_REG0confidential_SD2_RST 10
#define BUS_SOFT_RST_REG0confidential_SD1_RST 9
#define BUS_SOFT_RST_REG0confidential_SD0_RST 8
#define BUS_SOFT_RST_REG0confidential_DMA_RST 6
#define BUS_SOFT_RST_REG0confidential_CE_RST 5

// BUS_SOFT_RST_REG1
#define BUS_SOFT_RST_REG1 0x02C4
#define BUS_SOFT_RST_REG1_DBGSYS_RST 31
#define BUS_SOFT_RST_REG1_SPINLOCK_RST 22
#define BUS_SOFT_RST_REG1_MSGBOX_RST 21
#define BUS_SOFT_RST_REG1_GPU_RST 20
#define BUS_SOFT_RST_REG1_DE_RST 12
#define BUS_SOFT_RST_REG1_HDMI1_RST 11
#define BUS_SOFT_RST_REG1_HDMI0_RST 10
#define BUS_SOFT_RST_REG1_TVE_RST 9
#define BUS_SOFT_RST_REG1_CSI_RST 8
#define BUS_SOFT_RST_REG1_DEINTERLACE_RST 5
#define BUS_SOFT_RST_REG1_TCON1_RST 4
#define BUS_SOFT_RST_REG1_TCON0_RST 3
#define BUS_SOFT_RST_REG1_VE_RST 0

// BUS_SOFT_RST_REG2
#define BUS_SOFT_RST_REG2 0x02C8
#define BUS_SOFT_RST_REG2_EPHY_RST 2

// BUS_SOFT_RST_REG3
#define BUS_SOFT_RST_REG3 0x02D0
#define BUS_SOFT_RST_REG3_I2S_PCM_2_RST 14
#define BUS_SOFT_RST_REG3_I2S_PCM_1_RST 13
#define BUS_SOFT_RST_REG3_I2S_PCM_0_RST 12
#define BUS_SOFT_RST_REG3_THS_RST 8
#define BUS_SOFT_RST_REG3_OWA_RST 1
#define BUS_SOFT_RST_REG3_AC_RST 0

// BUS_SOFT_RST_REG4
#define BUS_SOFT_RST_REG4 0x02D8
#define BUS_SOFT_RST_REG4_SCR_RST 20
#define BUS_SOFT_RST_REG4_UART3_RST 19
#define BUS_SOFT_RST_REG4_UART2_RST 18
#define BUS_SOFT_RST_REG4_UART1_RST 17
#define BUS_SOFT_RST_REG4_UART0_RST 16
#define BUS_SOFT_RST_REG4_TWI2_RST 2
#define BUS_SOFT_RST_REG4_TWI1_RST 1
#define BUS_SOFT_RST_REG4_TWI0_RST 0

// CCU_SEC_SWITCH_REG
#define CCU_SEC_SWITCH_REG 0x02F0
#define CCU_SEC_SWITCH_REG_MBUS_SEC 2
#define CCU_SEC_SWITCH_REG_BUS_SEC 1
#define CCU_SEC_SWITCH_REG_PLL_SEC 0

// PS_CTRL_REGconfidential
#define PS_CTRL_REGconfidential 0x0300
#define PS_CTRL_REGconfidential_DET_FIN 7
#define PS_CTRL_REGconfidential_DLY_SEL 6
#define PS_CTRL_REGconfidential_OSC_SEL_HIGH 5
#define PS_CTRL_REGconfidential_OSC_SEL_LOW 4
#define PS_CTRL_REGconfidential_TIME_DET_HIGH 3
#define PS_CTRL_REGconfidential_TIME_DET_LOW 1
#define PS_CTRL_REGconfidential_MOD_EN 0

// PS_CNT_REG
#define PS_CNT_REG 0x0304
#define PS_CNT_REG_PS_CNT_HIGH 15
#define PS_CNT_REG_PS_CNT_LOW 0
