//
// IDMAC registers
// SD/MMC x registers
//

#pragma once

// for base register addr
#include <reg/regs_base.h>

//
// IDMAC registers
//

// DES0
#define DES0_DES_OWN_FLAG 31
#define DES0_ERROR_FLAG 30
#define DES0_CHAIN_MOD 4
#define DES0_FIRST_FLAG 3
#define DES0_LAST_FLAG 2
#define DES0_CURR_TXRX_OVER_INT_DIS 1

// DES1
#define DES1_BUFF_SIZE 0

// DES2
#define DES2_BUFF_ADDR 0

// DES3
#define DES3_NEXT_DESC_ADDR 0

//
// SD/MMC registers
//

// SD_CTRL
#define SD_GCTL 0x0000
#define SD_GCTL_FIFO_AC_MOD 31
#define SD_GCTL_DDR_MOD_SEL 10
#define SD_GCTL_CD_DBC_ENB 8
#define SD_GCTL_DMA_ENB 5
#define SD_GCTL_INT_ENB 4
#define SD_GCTL_FIFO_RST 1
#define SD_GCTL_SOFT_RST 0

// SD_CLKDIV
#define SD_CLKDIV 0x0004
#define SD_CLKDIV_MASK_DATA0 31
#define SD_CLKDIV_CCLK_CTRL 17
#define SD_CLKDIV_CCLK_ENB 16
#define SD_CLKDIV_CCLK_DIV_HIGH 7
#define SD_CLKDIV_CCLK_DIV_LOW 0

// SD_TMOUT
#define SD_TMOUT 0x0008
#define SD_TMOUT_DTO_LMT_HIGH 31
#define SD_TMOUT_DTO_LMT_LOW 8
#define SD_TMOUT_RTO_LMT_HIGH 7
#define SD_TMOUT_RTO_LMT_LOW 0

// SD_CTYPE
#define SD_CTYPE 0x000c
#define SD_CTYPE_CARD_WID_HIGH 1
#define SD_CTYPE_CARD_WID_LOW 0

// SD_BLKSIZ
#define SD_BLKSIZ 0x0010
#define SD_BLKSIZ_BLK_SZ_HIGH 15
#define SD_BLKSIZ_BLK_SZ_LOW 0

// SD_BYTCNT
#define SD_BYTCNT 0x0014
#define SD_BYTCNT_BYTE_CNT_HIGH 31
#define SD_BYTCNT_BYTE_CNT_LOW 0

// SD_CMD
#define SD_CMD 0x0018
#define SD_CMD_CMD_LOAD 31
#define SD_CMD_U 29
#define SD_CMD_VOL_SW 28
#define SD_CMD_BOOT_ABT 27
#define SD_CMD_EXP_BOOT_ACK 26
#define SD_CMD_BOOT_MOD_HIGH 25
#define SD_CMD_BOOT_MOD_LOW 24
#define SD_CMD_PRG_CLK 21
#define SD_CMD_SEND_INIT_SEQ 15
#define SD_CMD_STOP_ABT_CMD 14
#define SD_CMD_WAIT_PRE_OVER 13
#define SD_CMD_STOP_CMD_FLAG 12
#define SD_CMD_TRANS_MODE 11
#define SD_CMD_TRANS_DIR 10
#define SD_CMD_DATA_TRANS 9
#define SD_CMD_CHK_RESP_CRC 8
#define SD_CMD_LONG_RESP 7
#define SD_CMD_RESP_RCV 6
#define SD_CMD_CMD_IDX_HIGH 5
#define SD_CMD_CMD_IDX_LOW 0

// SD_CMDARG
#define SD_CMDARG 0x001c
#define SD_CMDARG_CMD_ARG_HIGH 31
#define SD_CMDARG_CMD_ARG_LOW 0

// SD_RESP0
#define SD_RESP0 0x0020
#define SD_RESP0_CMD_RESP0_HIGH 31
#define SD_RESP0_CMD_RESP0_LOW 0

// SD_RESP1
#define SD_RESP1 0x0024
#define SD_RESP1_CMD_RESP1_HIGH 31
#define SD_RESP1_CMD_RESP1_LOW 0

// SD_RESP2
#define SD_RESP2 0x0028
#define SD_RESP2_CMD_RESP2_HIGH 31
#define SD_RESP2_CMD_RESP2_LOW 0

// SD_RESP3
#define SD_RESP3 0x002C
#define SD_RESP3_CMD_RESP3_HIGH 31
#define SD_RESP3_CMD_RESP3_LOW 0

// SD_INTMASK
#define SD_INTMASK 0x0030
#define SD_INTMASK_INT_MASK_HIGH 31
#define SD_INTMASK_INT_MASK_LOW 0

// SD_MINTSTS
#define SD_MINTSTS 0x0034
#define SD_MINTSTS_MSKD_ISTA_HIGH 31
#define SD_MINTSTS_MSKD_ISTA_LOW 0

// SD_RINTSTS
#define SD_RINTSTS 0x0038
#define SD_RINTSTS_RAW_ISTA_HIGH 31
#define SD_RINTSTS_RAW_ISTA_LOW 0

// SD_STATUS
#define SD_STATUS 0x003C
#define SD_STATUS_DMA_REQ 31
#define SD_STATUS_FIFO_LEVEL_HIGH 21
#define SD_STATUS_FIFO_LEVEL_LOW 17
#define SD_STATUS_RESP_IDX_HIGH 16
#define SD_STATUS_RESP_IDX_LOW 11
#define SD_STATUS_FSM_BUSY 10
#define SD_STATUS_CARD_BUSY 9
#define SD_STATUS_CARD_PRESENT 8
#define SD_STATUS_FSM_STA_HIGH 7
#define SD_STATUS_FSM_STA_LOW 4
#define SD_STATUS_FIFO_FULL 3
#define SD_STATUS_FIFO_EMPTY 2
#define SD_STATUS_FIFO_TX_LEVEL 1
#define SD_STATUS_FIFO_RX_LEVEL 0

// SD_FIFOTH
#define SD_FIFOTH 0x0040
#define SD_FIFOTH_BSIZE_OF_TRANS_HIGH 30
#define SD_FIFOTH_BSIZE_OF_TRANS_LOW 28
#define SD_FIFOTH_TX_TL_HIGH 4
#define SD_FIFOTH_TX_TL_LOW 0

// SD_FUNS
#define SD_FUNS 0x0044
#define SD_FUNS_ABT_RDATA 2
#define SD_FUNS_READ_WAIT 1
#define SD_FUNS_HOST_SEND_MMC_IRQRESQ 0

// SD_A12A
#define SD_A12A 0x0058
#define SD_A12A_SD_A12A_HIGH 0
#define SD_A12A_SD_A12A_LOW 15

// SD_NTSR_REG
#define SD_NTSR_REG 0x005C
#define SD_NTSR_REG_MODE_SELEC 31
#define SD_NTSR_REG_SAMPLE_TIMING_PHASE_HIGH 30
#define SD_NTSR_REG_SAMPLE_TIMING_PHASE_LOW 6
#define SD_NTSR_REG_OUTPUT_TIMING_PHASE_HIGH 1
#define SD_NTSR_REG_OUTPUT_TIMING_PHASE_LOW 0

// SD_HWRST
#define SD_HWRST 0x0078
#define SD_HWRST_HW_RESET 0

// SD_BUS_MODE
#define SD_BUS_MODE 0x0080
#define SD_BUS_MODE_DES_LOAD_CTRL 31
#define SD_BUS_MODE_PRG_BURST_LEN_HIGH 10
#define SD_BUS_MODE_PRG_BURST_LEN_LOW 8
#define SD_BUS_MODE_IDMAC_ENB 7
#define SD_BUS_MODE_DES_SKIP_LEN_HIGH 6
#define SD_BUS_MODE_DES_SKIP_LEN_LOW 2
#define SD_BUS_MODE_FIX_BUST_CTRL 1
#define SD_BUS_MODE_IDMAC_RST 0

// SD_DLBA
#define SD_DLBA 0x0084
#define SD_DLBA_DES_BASE_ADDR_HIGH 31
#define SD_DLBA_DES_BASE_ADDR_LOW 0

// SD_DSR
#define SD_DSR 0x0088
#define SD_DSR_DMAC_FSM_STA_HIGH 16
#define SD_DSR_DMAC_FSM_STA_LOW 13
#define SD_DSR_DMAC_ERR_STA_HIGH 12
#define SD_DSR_DMAC_ERR_STA_LOW 10
#define SD_DSR_ABN_INT_SUM 9
#define SD_DSR_NOR_INT_SUM 8
#define SD_DSR_ERR_FLAG_SUM 5
#define SD_DSR_DES_UNAVL_INT 4
#define SD_DSR_FATAL_BERR_INT 2
#define SD_DSR_RX_INT 1
#define SD_DSR_TX_INT 0

// SD_IDIE_REG
#define SD_IDIE_REG 0x008C
#define SD_IDIE_REG_ABN_INT_ENB 9
#define SD_IDIE_REG_NOR_INT_ENB 8
#define SD_IDIE_REG_ERR_SUM_INT_ENB 5
#define SD_IDIE_REG_DES_UNAVL_INT_ENB 4
#define SD_IDIE_REG_FERR_INT_ENB 2
#define SD_IDIE_REG_RX_INT_ENB 1
#define SD_IDIE_REG_TX_INT_ENB 0

// SD_THLD_REG
#define SD_THLD_REG 0x0100
#define SD_THLD_REG_CARD_RD_THLD_HIGH 27
#define SD_THLD_REG_CARD_RD_THLD_LOW 16
#define SD_THLD_REG_CARD_RD_THLD_ENB 0

// EMMC_DDR_SBIT_DET_REG
#define EMMC_DDR_SBIT_DET_REG 0x010C
#define EMMC_DDR_SBIT_DET_REG_HALF_START_BIT 0

// RESP_CRC_REG
#define RESP_CRC_REG 0x0110
#define RESP_CRC_REG_RESP_CRC_HIGH 6
#define RESP_CRC_REG_RESP_CRC_LOW 0

// DATA7_CRC_REG
#define DATA7_CRC_REG 0x0114
#define DATA7_CRC_REG_DATA7_CRC_HIGH 31
#define DATA7_CRC_REG_DATA7_CRC_LOW 0

// DATA6_CRC_REG
#define DATA6_CRC_REG 0x0118
#define DATA6_CRC_REG_DATA6_CRC_HIGH 31
#define DATA6_CRC_REG_DATA6_CRC_LOW 0

// DATA5_CRC_REG
#define DATA5_CRC_REG 0x011c
#define DATA5_CRC_REG_DATA5_CRC_HIGH 31
#define DATA5_CRC_REG_DATA5_CRC_LOW 0

// DATA4_CRC_REG
#define DATA4_CRC_REG 0x0120
#define DATA4_CRC_REG_DATA4_CRC_HIGH 31
#define DATA4_CRC_REG_DATA4_CRC_LOW 0

// DATA3_CRC_REG
#define DATA3_CRC_REG 0x0124
#define DATA3_CRC_REG_DATA3_CRC_HIGH 31
#define DATA3_CRC_REG_DATA3_CRC_LOW 0

// DATA2_CRC_REG
#define DATA2_CRC_REG 0x0128
#define DATA2_CRC_REG_DATA2_CRC_HIGH 31
#define DATA2_CRC_REG_DATA2_CRC_LOW 0

// DATA1_CRC_REG
#define DATA1_CRC_REG 0x012c
#define DATA1_CRC_REG_DATA1_CRC_HIGH 31
#define DATA1_CRC_REG_DATA1_CRC_LOW 0

// DATA0_CRC_REG
#define DATA0_CRC_REG 0x0130
#define DATA0_CRC_REG_DATA0_CRC_HIGH 31
#define DATA0_CRC_REG_DATA0_CRC_LOW 0

// CRC_STA_REG
#define CRC_STA_REG 0x0134
#define CRC_STA_REG_CRC_STA_HIGH 2
#define CRC_STA_REG_CRC_STA_LOW 0

// SD_FIFO_REG
#define SD_FIFO_REG 0x0200
#define SD_FIFO_REG_TX_HIGH 31
#define SD_FIFO_REG_TX_LOW 0
