//
// IDMAC registers
// SD/MMC x registers
//

#pragma once

// for base register addr
#include <reg/regs_base.h>

//
// IDMAC registers
//

// DES0
#define DES0_DES_OWN_FLAG 31
#define DES0_ERROR_FLAG 30
#define DES0_CHAIN_MOD 4
#define DES0_FIRST_FLAG 3
#define DES0_LAST_FLAG 2
#define DES0_CURR_TXRX_OVER_INT_DIS 1

// DES1
#define DES1_BUFF_SIZE 0

// DES2
#define DES2_BUFF_ADDR 0

// DES3
#define DES3_NEXT_DESC_ADDR 0

//
// SD/MMC registers
//

#define SD_MMC0(reg) *(vu32ptr_t)(BASE_SD_MMC0 + (reg))
#define SD_MMC1(reg) *(vu32ptr_t)(BASE_SD_MMC1 + (reg))
#define SD_MMC2(reg) *(vu32ptr_t)(BASE_SD_MMC2 + (reg))

// SD_GCTL
#define SD_GCTL 0x0000
#define SD_GCTL_FIFO_AC_MOD 31
#define SD_GCTL_DDR_MOD_SEL 10
#define SD_GCTL_CD_DBC_ENB 8
#define SD_GCTL_DMA_ENB 5
#define SD_GCTL_INT_ENB 4
#define SD_GCTL_DMA_RST 2
#define SD_GCTL_FIFO_RST 1
#define SD_GCTL_SOFT_RST 0

// SD_CKCR
#define SD_CKCR 0x0004
#define SD_CKCR_MASK_DATA0 31
#define SD_CKCR_CCLK_CTRL 17
#define SD_CKCR_CCLK_ENB 16
#define SD_CKCR_CCLK_DIV_HIGH 7
#define SD_CKCR_CCLK_DIV_LOW 0

// SD_TMOR
#define SD_TMOR 0x0008
#define SD_TMOR_DTO_LMT_HIGH 31
#define SD_TMOR_DTO_LMT_LOW 8
#define SD_TMOR_RTO_LMT_HIGH 7
#define SD_TMOR_RTO_LMT_LOW 0

// SD_BWDR
#define SD_BWDR 0x000c
#define SD_BWDR_CARD_WID_HIGH 1
#define SD_BWDR_CARD_WID_LOW 0

// SD_BKSR
#define SD_BKSR 0x0010
#define SD_BKSR_BLK_SZ_HIGH 15
#define SD_BKSR_BLK_SZ_LOW 0

// SD_BYCR
#define SD_BYCR 0x0014
#define SD_BYCR_BYTE_CNT_HIGH 31
#define SD_BYCR_BYTE_CNT_LOW 0

// SD_CMDR
#define SD_CMDR 0x0018
#define SD_CMDR_CMD_LOAD 31
#define SD_CMDR_U 29
#define SD_CMDR_VOL_SW 28
#define SD_CMDR_BOOT_ABT 27
#define SD_CMDR_EXP_BOOT_ACK 26
#define SD_CMDR_BOOT_MOD_HIGH 25
#define SD_CMDR_BOOT_MOD_LOW 24
#define SD_CMDR_PRG_CLK 21
#define SD_CMDR_SEND_INIT_SEQ 15
#define SD_CMDR_STOP_ABT_CMD 14
#define SD_CMDR_WAIT_PRE_OVER 13
#define SD_CMDR_STOP_CMD_FLAG 12
#define SD_CMDR_TRANS_MODE 11
#define SD_CMDR_TRANS_DIR 10
#define SD_CMDR_DATA_TRANS 9
#define SD_CMDR_CHK_RESP_CRC 8
#define SD_CMDR_LONG_RESP 7
#define SD_CMDR_RESP_RCV 6
#define SD_CMDR_CMD_IDX_HIGH 5
#define SD_CMDR_CMD_IDX_LOW 0

// SD_CAGR
#define SD_CAGR 0x001c
#define SD_CAGR_CMD_ARG_HIGH 31
#define SD_CAGR_CMD_ARG_LOW 0

// SD_RESP0
#define SD_RESP0 0x0020
#define SD_RESP0_CMD_RESP0_HIGH 31
#define SD_RESP0_CMD_RESP0_LOW 0

// SD_RESP1
#define SD_RESP1 0x0024
#define SD_RESP1_CMD_RESP1_HIGH 31
#define SD_RESP1_CMD_RESP1_LOW 0

// SD_RESP2
#define SD_RESP2 0x0028
#define SD_RESP2_CMD_RESP2_HIGH 31
#define SD_RESP2_CMD_RESP2_LOW 0

// SD_RESP3
#define SD_RESP3 0x002C
#define SD_RESP3_CMD_RESP3_HIGH 31
#define SD_RESP3_CMD_RESP3_LOW 0

// SD_IMKR
#define SD_IMKR 0x0030
#define SD_IMKR_INT_MASK_HIGH 31
#define SD_IMKR_INT_MASK_LOW 0

// SD_MISR
#define SD_MISR 0x0034
#define SD_MISR_MSKD_ISTA_HIGH 31
#define SD_MISR_MSKD_ISTA_LOW 0

// SD_RISR
#define SD_RISR 0x0038
#define SD_RISR_RAW_ISTA_HIGH 31
#define SD_RISR_RAW_ISTA_LOW 0

// SD_STAR
#define SD_STAR 0x003C
#define SD_STAR_DMA_REQ 31
#define SD_STAR_FIFO_LEVEL_HIGH 21
#define SD_STAR_FIFO_LEVEL_LOW 17
#define SD_STAR_RESP_IDX_HIGH 16
#define SD_STAR_RESP_IDX_LOW 11
#define SD_STAR_FSM_BUSY 10
#define SD_STAR_CARD_BUSY 9
#define SD_STAR_CARD_PRESENT 8
#define SD_STAR_FSM_STA_HIGH 7
#define SD_STAR_FSM_STA_LOW 4
#define SD_STAR_FIFO_FULL 3
#define SD_STAR_FIFO_EMPTY 2
#define SD_STAR_FIFO_TX_LEVEL 1
#define SD_STAR_FIFO_RX_LEVEL 0

// SD_FWLR
#define SD_FWLR 0x0040
#define SD_FWLR_BSIZE_OF_TRANS_HIGH 30
#define SD_FWLR_BSIZE_OF_TRANS_LOW 28
#define SD_FWLR_TX_TL_HIGH 4
#define SD_FWLR_TX_TL_LOW 0

// SD_FUNS
#define SD_FUNS 0x0044
#define SD_FUNS_ABT_RDATA 2
#define SD_FUNS_READ_WAIT 1
#define SD_FUNS_HOST_SEND_MMC_IRQRESQ 0

// SD_A12A
#define SD_A12A 0x0058
#define SD_A12A_SD_A12A_HIGH 0
#define SD_A12A_SD_A12A_LOW 15

// SD_NTSR
#define SD_NTSR 0x005C
#define SD_NTSR_MODE_SELEC 31
#define SD_NTSR_SAMPLE_TIMING_PHASE_HIGH 30
#define SD_NTSR_SAMPLE_TIMING_PHASE_LOW 6
#define SD_NTSR_OUTPUT_TIMING_PHASE_HIGH 1
#define SD_NTSR_OUTPUT_TIMING_PHASE_LOW 0

// SD_HWRST
#define SD_HWRST 0x0078
#define SD_HWRST_HW_RESET 0

// SD_DMAC
#define SD_DMAC 0x0080
#define SD_DMAC_DES_LOAD_CTRL 31
#define SD_DMAC_PRG_BURST_LEN_HIGH 10
#define SD_DMAC_PRG_BURST_LEN_LOW 8
#define SD_DMAC_IDMAC_ENB 7
#define SD_DMAC_DES_SKIP_LEN_HIGH 6
#define SD_DMAC_DES_SKIP_LEN_LOW 2
#define SD_DMAC_FIX_BUST_CTRL 1
#define SD_DMAC_IDMAC_RST 0

// SD_DLBA
#define SD_DLBA 0x0084
#define SD_DLBA_DES_BASE_ADDR_HIGH 31
#define SD_DLBA_DES_BASE_ADDR_LOW 0

// SD_IDST
#define SD_IDST 0x0088
#define SD_IDST_DMAC_FSM_STA_HIGH 16
#define SD_IDST_DMAC_FSM_STA_LOW 13
#define SD_IDST_DMAC_ERR_STA_HIGH 12
#define SD_IDST_DMAC_ERR_STA_LOW 10
#define SD_IDST_ABN_INT_SUM 9
#define SD_IDST_NOR_INT_SUM 8
#define SD_IDST_ERR_FLAG_SUM 5
#define SD_IDST_DES_UNAVL_INT 4
#define SD_IDST_FATAL_BERR_INT 2
#define SD_IDST_RX_INT 1
#define SD_IDST_TX_INT 0

// SD_IDIE
#define SD_IDIE 0x008C
#define SD_IDIE_ABN_INT_ENB 9
#define SD_IDIE_NOR_INT_ENB 8
#define SD_IDIE_ERR_SUM_INT_ENB 5
#define SD_IDIE_DES_UNAVL_INT_ENB 4
#define SD_IDIE_FERR_INT_ENB 2
#define SD_IDIE_RX_INT_ENB 1
#define SD_IDIE_TX_INT_ENB 0

// SD_THLDC
#define SD_THLDC 0x0100
#define SD_THLDC_CARD_RD_THLD_HIGH 27
#define SD_THLDC_CARD_RD_THLD_LOW 16
#define SD_THLDC_CARD_RD_THLD_ENB 0

// SD_DSBD
#define SD_DSBD 0x010C
#define SD_DSBD_HALF_START_BIT 0

// SD_RES_CRC
#define SD_RES_CRC 0x0110
#define SD_RES_CRC_RESP_CRC_HIGH 6
#define SD_RES_CRC_RESP_CRC_LOW 0

// SD_DATA7_CRC
#define SD_DATA7_CRC 0x0114
#define SD_DATA7_CRC_DATA7_CRC_HIGH 31
#define SD_DATA7_CRC_DATA7_CRC_LOW 0

// SD_DATA6_CRC
#define SD_DATA6_CRC 0x0118
#define SD_DATA6_CRC_DATA6_CRC_HIGH 31
#define SD_DATA6_CRC_DATA6_CRC_LOW 0

// SD_DATA5_CRC
#define SD_DATA5_CRC 0x011c
#define SD_DATA5_CRC_DATA5_CRC_HIGH 31
#define SD_DATA5_CRC_DATA5_CRC_LOW 0

// SD_DATA4_CRC
#define SD_DATA4_CRC 0x0120
#define SD_DATA4_CRC_DATA4_CRC_HIGH 31
#define SD_DATA4_CRC_DATA4_CRC_LOW 0

// SD_DATA3_CRC
#define SD_DATA3_CRC 0x0124
#define SD_DATA3_CRC_DATA3_CRC_HIGH 31
#define SD_DATA3_CRC_DATA3_CRC_LOW 0

// SD_DATA2_CRC
#define SD_DATA2_CRC 0x0128
#define SD_DATA2_CRC_DATA2_CRC_HIGH 31
#define SD_DATA2_CRC_DATA2_CRC_LOW 0

// SD_DATA1_CRC
#define SD_DATA1_CRC 0x012c
#define SD_DATA1_CRC_DATA1_CRC_HIGH 31
#define SD_DATA1_CRC_DATA1_CRC_LOW 0

// SD_DATA0_CRC
#define SD_DATA0_CRC 0x0130
#define SD_DATA0_CRC_DATA0_CRC_HIGH 31
#define SD_DATA0_CRC_DATA0_CRC_LOW 0

// SD_CRC_STA
#define SD_CRC_STA 0x0134
#define SD_CRC_STA_CRC_STA_HIGH 2
#define SD_CRC_STA_CRC_STA_LOW 0

// SD_FIFO
#define SD_FIFO 0x0200
#define SD_FIFO_TX_HIGH 31
#define SD_FIFO_TX_LOW 0

//
// Common register values
//

#define SD_GCTL_RESET                                                          \
  ((1 << SD_GCTL_SOFT_RST) | (1 << SD_GCTL_FIFO_RST) | (1 << SD_GCTL_DMA_RST))
